### ISSUE TITLE
Faulty import of other HeartPredict scripts

### ISSUE THREAD

**Issue by valbo451** [HeartPredict/HeartPredict#43]
During my attempts to create an OOP version for descriptive.py, I looked for orientation at the scripts ml.py and data.py especially regarding the import of objects from other modules. During this, I have encountered an import bug.

By running "ml.py" I got the import error: "_ModuleNotFoundError: No module named 'heartpredict'_" (see below).

I reckoned there is a problem with the relative import call at line 8: "_from heartpredict.backend.data import MLData_"

In the descriptive.py script, I simply used "from data import ProjectData" for example and it worked fine. This is an error, right? Or am I missing something here?

<img width="1391" alt="import_bug_heartpredict" src="https://github.com/HeartPredict/HeartPredict/assets/133235403/37e0ca50-d6c8-46c6-8ba3-f71e924a1033">

**Comment by iron3oxide** [comment]
You need to install the heartpredict package we're developing. If you use rye, this should be achieved by running `rye sync`, otherwise you can do `pip install .`

**Comment by valbo451** [comment]
Okay, I will try the import of the heartpredict package. 

There's another thing. I tried to run the "descriptive.py" and because it imports the ProjectData from "data.py", I got the error "_TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'_"

I looked into data.py and the error results from the function definition of "__scale_input_features_" (see below). How can we fix this?

<img width="719" alt="data_faulty_function" src="https://github.com/HeartPredict/HeartPredict/assets/133235403/db3855cf-38b2-4d71-afb9-bfad964af4a5">

**Comment by iron3oxide** [comment]
I believe that stems from you using Python 3.9, we could fix it by using typing.Union instead.

**Comment by iron3oxide** [comment]
@HokageM do we really even need x_valid to be optional? Is there a model without x_valid?

**Comment by HokageM** [comment]
@iron3oxide 

https://github.com/HeartPredict/HeartPredict/blob/main/src/heartpredict/backend/data.py

For the scaled_dataset it is called without x_valid

**Comment by HokageM** [comment]
The survival module uses this scaled_dataset
